version: '3'
services:
  postgres:
    image: 'postgres:15.3-alpine3.18'
    restart: unless-stopped
    container_name: 'java-postgres'
    environment:
      - POSTGRES_USER=developerTP
      - POSTGRES_PASSWORD=BX2VYtCMBU6J4aS7JkRBNM9yvfqsJu
      - POSTGRES_DB=taggy-pet-database
    ports:
      - 15432:5432

  app:
    build: ./
    container_name: 'taggy-pet-application'
    ports:
      - 8080:8080
    links:
      - 'postgres:taggy-pet-database'