version: '3'

services:
  postgres:
    image: 'postgres:15.3-alpine3.18'
    restart: unless-stopped
    container_name: 'taggy-pet-postgres'
    environment:
      - POSTGRES_USER=developerTP
      - POSTGRES_PASSWORD=BX2VYtCMBU6J4aS7JkRBNM9yvfqsJu
      - POSTGRES_DB=taggy-pet-database
    ports:
      - '15432:5432'
    volumes:
      - taggy-pet-postgres-volume:/var/lib/postgresql/data
    networks:
      - tp-network

  app:
    build: ./
    container_name: 'taggy-pet-application'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - tp-network

  nginx:
    image: nginx
    container_name: 'taggy-pet-nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /Users/mac/SberProject:/etc/nginx/ssl # TODO: change mounting directory
    depends_on:
      - app
    networks:
      - tp-network

volumes:
  taggy-pet-postgres-volume:
    driver: local

networks:
  tp-network:
    driver: bridge
